# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sharing IT tech
email: torreswoo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  기술은 공유 되어야한다.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://torreswoo.github.io/" # the base hostname & protocol for your site
github_username: torreswoo
linkedin_username: jongho-woo-b92098b4
facebook_username: torres.woo

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  sass_dir: assets/_sass
  style: compressed

images: '/assets/images'

# GA
google_analytics: "UA-96861113-1"